Repository zero-to-mastery/ZtM-Job-Board, pull requests merged in 2020-11, with the labels that each got.

#1605 Update persons.js
  src/assets/persons.js
Labels: Conflict Present, hacktoberfest-accepted

#1618 Added my details to persons.js file
  src/assets/persons.js
Labels: Stale

#1608 add_my_name
  src/assets/persons.js
Labels: hacktoberfest-accepted
