Repository zero-to-mastery/ZtM-Job-Board, pull requests merged in 2022-04, with the labels that each got.

#2250 Submission
  Submissions/blehjo.json
Labels: Stale

#2251 Add Teetee-lab.json
  Submissions/Teetee-lab.json
Labels: Stale

#2255 profile has been added 🔥
  Submissions/milan960.json
  src/assets/persons.json
Labels: changes requested

#2233 add my name to job board
  Submissions/kennedy-ogutu.json
Labels: Stale, changes requested
